### ISSUE TITLE
[BUG] latest release (v0.8.7) doesn't build

### ISSUE THREAD

**Issue by knoellle** [DioCrafts/OxiCloud#649]
## Description

As previously mentioned in https://github.com/AtalayaLabs/OxiCloud/pull/642#issuecomment-5081307387, the latest release (v0.8.7) doesn't build.
As far as I can tell, the issue was introduced in #641 and fixed in #642.
However, the release tag sits in between those two merges, leaving it broken.

This also break automatic deployment/updating tools like https://community-scripts.org/scripts/oxicloud

## To Reproduce

Steps to reproduce the behavior, adapted from README:
```sh
git clone https://github.com/AtalayaLabs/OxiCloud.git
cd OxiCloud
cp example.env .env

git checkout v0.8.7
cargo run
```
Result:
```
error[E0063]: missing fields `is_favorite` and `is_shared` in initializer of `FolderDto`
  --> src/application/services/mount_dto.rs:55:5
   |
55 |     FolderDto {
   |     ^^^^^^^^^ missing `is_favorite` and `is_shared`

[...]
```

Issue was also caught by CI checks on the tagged commit:
https://github.com/AtalayaLabs/OxiCloud/actions/runs/29892256104/job/88834845384

## Expected Behavior

Program builds/runs

## Environment

- OS: Arch Linux
- Browser: -
- OxiCloud Version: 0.8.7
- Rust Version: 1.97.1

## Possible Solution

Please make a new release that builds.

Additionally: Add build check to release CI job to prevent issues like this in the future.

**Comment by EdouardVanbelle** [comment]
cc @DioCrafts 
this is also explained in https://github.com/AtalayaLabs/OxiCloud/issues/632
a CI to prevent the creation of the tag will prevent future issue

**Comment by EdouardVanbelle** [comment]
Hello @DioCrafts seems this option could solve any future similar issues:

on your Github space:
   Settings → Branches → main → Require merge queue → merge_group event handling in CI workflows
